public enum InstructionSet {
    LOAD_VALUE,
    INCREMENT,
    ADD_VALUE,
    SHOW_REG,
    SLEEP,
    TERMINATE,
    MAP_SHARED_MEM,
    ACQUIRE_LOCK,
    RELEASE_LOCK,
    SIGNAL_EVENT,
    WAIT_EVENT,
    ALLOC,
    FREE_MEMORY,
    MEMORY_STATS,
    WRITE_MEM
}